name: Build Chrome Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: 🧹 Lint JS (optional, only if ESLint is configured)
        run: |
          if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
            npx eslint . || true
          else
            echo "No ESLint config found, skipping lint"
          fi

      - name: 📦 Create ZIP of the extension
        run: |
          mkdir -p dist
          cd browser-extension
          zip -r ../dist/extension.zip ./*
          cd ..

      - name: 📤 Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-zip
          path: dist/extension.zip
